# GitHub sponsors and external funding options. Edit to suit.
# github: [YOUR_GITHUB_USERNAME]
# patreon: # username
# open_collective: # username
# ko_fi: # username
# liberapay: # username
# custom: ["https://transformative.studio"]
